version: 0.2
phases: 
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest discover tests
artifacts:
  files:
    - app.py
    - requirements.txt
